/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.awt.Point;
import javax.swing.text.*;
import java.util.Enumeration;
import javax.swing.AbstractButton;


import java.util.Arrays;

/**
 *
 * @author Lourens
 */
public class StartGUI extends javax.swing.JFrame {

    /**
     * Creates new form StartGUI
     */
    public StartGUI() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGF = new javax.swing.ButtonGroup();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonShowProperties = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonGF2 = new javax.swing.JRadioButton();
        jRadioButtonGF3 = new javax.swing.JRadioButton();
        jRadioButtonGF8 = new javax.swing.JRadioButton();
        jButtonGMatrix = new javax.swing.JButton();
        jButtonShowInfo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButtonGenCW = new javax.swing.JButton();
        jButtonSendZero = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jButtonRowDecode = new javax.swing.JButton();
        jButtonColumnDecode = new javax.swing.JButton();
        jError = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jRowBox = new javax.swing.JComboBox<>();
        jColumnBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setColumns(10);
        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonShowProperties.setText("Show Properties");
        jButtonShowProperties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowPropertiesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("X PRODUCT CODES");

        buttonGroupGF.add(jRadioButtonGF2);
        jRadioButtonGF2.setSelected(true);
        jRadioButtonGF2.setText("GF 2");
        jRadioButtonGF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGF2ActionPerformed(evt);
            }
        });

        buttonGroupGF.add(jRadioButtonGF3);
        jRadioButtonGF3.setText("GF 3");
        jRadioButtonGF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGF3ActionPerformed(evt);
            }
        });

        buttonGroupGF.add(jRadioButtonGF8);
        jRadioButtonGF8.setText("GF 8");
        jRadioButtonGF8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGF8ActionPerformed(evt);
            }
        });

        jButtonGMatrix.setText("Show G Matrix");
        jButtonGMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGMatrixActionPerformed(evt);
            }
        });

        jButtonShowInfo.setText("Show Info Words");
        jButtonShowInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowInfoActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setAutoscrolls(false);
        jScrollPane2.setViewportView(jTextArea2);

        jButtonGenCW.setText("Generate Codewords");
        jButtonGenCW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenCWActionPerformed(evt);
            }
        });

        jButtonSendZero.setText("Send All Zero Word");
        jButtonSendZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendZeroActionPerformed(evt);
            }
        });

        jTextArea3.setColumns(10);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jTextArea4.setColumns(10);
        jTextArea4.setRows(5);
        jScrollPane5.setViewportView(jTextArea4);

        jTextArea5.setColumns(10);
        jTextArea5.setRows(5);
        jScrollPane6.setViewportView(jTextArea5);

        jButtonRowDecode.setText("Decode Row");
        jButtonRowDecode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRowDecodeActionPerformed(evt);
            }
        });

        jButtonColumnDecode.setText("Decode Column");
        jButtonColumnDecode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColumnDecodeActionPerformed(evt);
            }
        });

        jError.setText("0.2");
        jError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jErrorActionPerformed(evt);
            }
        });

        jLabel2.setText("Error Probability");

        jRowBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(7; 4; 3)", "(8; 2; 5)" }));
        jRowBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRowBoxActionPerformed(evt);
            }
        });

        jColumnBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(7; 4; 3)", "(8; 2; 5)" }));

        jLabel3.setText("Row Code");

        jLabel4.setText("Column Code");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonGF2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jRadioButtonGF3)
                        .addGap(49, 49, 49)
                        .addComponent(jRadioButtonGF8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonGMatrix, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButtonShowInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonGenCW, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jButtonShowProperties, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSendZero))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRowDecode))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonColumnDecode)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jRowBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jColumnBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jError, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonGF2)
                    .addComponent(jRadioButtonGF3)
                    .addComponent(jRadioButtonGF8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRowBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jColumnBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonShowProperties)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonShowInfo)
                            .addComponent(jButtonSendZero)
                            .addComponent(jButtonRowDecode)
                            .addComponent(jButtonColumnDecode))
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGMatrix)
                    .addComponent(jButtonGenCW))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane5)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
 
    GFx objGF2 = new GFx (2);
    GFx objGF3 = new GFx (3);
    GFx objGF8 = new GFx (8);
    
    Integer [][] G_7_4_3 = new Integer[][] { {1,0,0,0,1,1,1}, {0,1,0,0,1,1,0}, {0,0,1,0,1,0,1}, {0,0,0,1,0,1,1} };
    Integer [][] G_8_2_5 = new Integer [][] { {1,0,1,1,1,1,0,0}, {0,1,1,1,0,0,1,1} };
    
    public int getSelectedGF (){
        String str = "";
        char lastChar;
        int GF = 0;
        
        for (Enumeration <AbstractButton> buttons = buttonGroupGF.getElements(); buttons.hasMoreElements();){
            AbstractButton button = buttons.nextElement();
            
            if (button.isSelected()){
                str = button.getText();
                lastChar = str.charAt(str.length() -1);
                GF = Character.getNumericValue(lastChar);
                //System.out.println("Selected GF = " + GF);
                return GF;
            }
        }
        //System.out.println("-1, getSelectedGF() failed");
        return -1;
        
    }
    
    public void selectG () {
        
        if (jRowBox.getSelectedItem() == "(7; 4; 3)") {
            objGF2.setG(G_7_4_3, 7, 4, 3);
        } else if (jRowBox.getSelectedItem() == "(8; 2; 5)"){
            objGF2.setG(G_8_2_5, 8, 2, 5);
        }
        
        if (jColumnBox.getSelectedItem() == "(7; 4; 3)") {
            objGF2.setGColumn(G_7_4_3, 7, 4, 3);
        } else if (jColumnBox.getSelectedItem() == "(8; 2; 5)"){
            objGF2.setGColumn(G_8_2_5, 8, 2, 5);
        }
        
    }
     
    private void jButtonShowPropertiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowPropertiesActionPerformed
        // TODO add your handling code here:
        int GF = getSelectedGF();
        
        if (GF < 0){
            return;
        }
        else if (GF == 2){
            jTextArea1.setText(objGF2.printProperties());
        } else if (GF == 3){
            jTextArea1.setText(objGF3.printProperties());
        } else if (GF == 8){
            jTextArea1.setText(objGF8.printProperties());
        }    
    }//GEN-LAST:event_jButtonShowPropertiesActionPerformed

    private void jRadioButtonGF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGF2ActionPerformed
        // TODO add your handling code here:
       
       
    }//GEN-LAST:event_jRadioButtonGF2ActionPerformed

    private void jRadioButtonGF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonGF3ActionPerformed

    private void jButtonGMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGMatrixActionPerformed
        // TODO add your handling code here:
        int GF = getSelectedGF ();
        if (GF < 0 ){
            return;
        } else if (GF == 2){
            selectG();
            
            String str2 = "";
            str2 += "ROW MATRIX = \n" + objGF2.printG();
            str2 += "\n COLUMN MATRIX = \n" + objGF2.printArray(objGF2.getGColumn());
            jTextArea1.setText(str2);
        } else if (GF == 3){
            jTextArea1.setText(objGF3.printG());
        } else if (GF == 8){
            jTextArea1.setText(objGF8.printG());
        }
    }//GEN-LAST:event_jButtonGMatrixActionPerformed

    private void jRadioButtonGF8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGF8ActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jRadioButtonGF8ActionPerformed

    private void jButtonShowInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowInfoActionPerformed
        // TODO add your handling code here:
        int GF = getSelectedGF ();
        if (GF < 0 ){
            return;
        } else if (GF == 2){
            objGF2.generateInfo();
            
            String str2 = "Amount of infowords = " + objGF2.getInfo().length;
            str2 += "\nLength of infoword = " + objGF2.getInfo()[0].length + "\n\n";
           
            str2 += objGF2.printArray(objGF2.getInfo());
            objGF2.generateInfoColumn();
            str2 += "\n\n" + objGF2.printArray(objGF2.getInfoColumn());
            
            jTextArea2.setText(str2);
        } else if (GF == 3){   
            String str3 = "Amount of infowords = " + objGF3.getInfo().length;
            str3 += "\nLength of infoword = " + objGF3.getInfo()[0].length + "\n\n";
            jTextArea2.setText(str3 + objGF3.printArray(objGF3.getInfo()));
              
        } else if (GF == 8){
            objGF8.generateInfoGF8();
            
            String str8 = "Amount of infowords = " + objGF8.getInfo().length;
            str8 += "\nLength of infoword = " + objGF8.getInfo()[0].length + "\n\n";
            jTextArea2.setText(str8 + objGF8.printArray(objGF8.getInfo() ));
            
            // Scroll to top. 
            jScrollPane2.getViewport().setViewPosition(new Point(0,0));
            
            DefaultCaret caret = (DefaultCaret) jTextArea2.getCaret();
            caret.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
        }        
    }//GEN-LAST:event_jButtonShowInfoActionPerformed

    private void jButtonGenCWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenCWActionPerformed
        // TODO add your handling code here:
        int GF = getSelectedGF ();
        if (GF < 0 ){
            return;
        } else if (GF == 2){
            objGF2.generateCW();
            String str2 = "";
            str2 += "Length of a codeword = " + objGF2.getCW()[0].length;
            
            str2 += "\n\n" + objGF2.printArray(objGF2.getCW());
            
            // Column with (7,4,4) test
            objGF2.generateCWColumn();
  
            str2 += "\n\nCOLUMN CODEWORD TEST \n\n" + objGF2.printArray(objGF2.getCWColumn());
            jTextArea2.setText(str2);
        } else if (GF == 3){
            objGF3.generateCW();
            String str3 = "";
            str3 += "Length of a codeword = " + objGF3.getCW()[0].length;
            jTextArea2.setText(str3 + "\n\n" + objGF3.printArray(objGF3.getCW()));
        } else if (GF == 8){
            objGF8.generateCWGF8();
            String str8 = "";
            str8 += "Length of a codeword = " + objGF8.getCW()[0].length;
            
            jTextArea2.setText(str8 + "\n\n" + objGF8.printArray(objGF8.getCW()));
            
            jScrollPane2.getViewport().setViewPosition(new Point(0,0));
            DefaultCaret caret = (DefaultCaret) jTextArea2.getCaret();
            caret.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
        }           
    }//GEN-LAST:event_jButtonGenCWActionPerformed

    private void jButtonSendZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendZeroActionPerformed
        // TODO add your handling code here:
        int GF = getSelectedGF ();
        
        double p = getProbability ();
        
        if (GF < 0 ){
            return;
        } else if (GF == 2){
            objGF2.fillProbability(p);
            jTextArea3.setText(objGF2.printArray(objGF2.getSent()));
        } else if (GF == 3){
            objGF3.fillProbability(p);
            jTextArea3.setText(objGF3.printArray(objGF3.getSent()));
        } else if (GF == 8){
            //objGF8.fillTest();
            objGF8.fillProbability(p);
            jTextArea3.setText(objGF8.printArray(objGF8.getSent()));
        }               
    }//GEN-LAST:event_jButtonSendZeroActionPerformed

    private void jButtonRowDecodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRowDecodeActionPerformed
        // TODO add your handling code here:
        int GF = getSelectedGF ();
        if (GF < 0 ){
            return;
        } else if (GF == 2){
            objGF2.rowDecode();
            jTextArea4.setText(objGF2.printArray(objGF2.getSent()));
        } else if (GF == 3){
            objGF3.rowDecode();
            jTextArea4.setText(objGF3.printArray(objGF3.getSent()));
        } else if (GF == 8){
            objGF8.rowDecode();
            jTextArea4.setText(objGF8.printArray(objGF8.getSent()));
        }      
    }//GEN-LAST:event_jButtonRowDecodeActionPerformed

    private void jButtonColumnDecodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColumnDecodeActionPerformed

        int GF = getSelectedGF ();
        if (GF < 0 ){
            return;
        } else if (GF == 2){
            objGF2.columnDecode();
            jTextArea5.setText(objGF2.printArray(objGF2.getSent()));
        } else if (GF == 3){
            objGF3.columnDecode();
            jTextArea5.setText(objGF3.printArray(objGF3.getSent()));
        } else if (GF == 8){
            objGF8.columnDecode();
            jTextArea5.setText(objGF8.printArray(objGF8.getSent()));
        }      
    }//GEN-LAST:event_jButtonColumnDecodeActionPerformed

    private double getProbability () {
        String str = jError.getText();
        double p = Double.parseDouble(str);
        
        if (p < 0 || p > 0.5){
            System.out.println("P must be between 0 and 0.5 and is: " + p);
        }
        return p;
    }
    
    private void jErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jErrorActionPerformed
        // TODO add your handling code here:
        
        String str = jError.getText();
        double p = Double.parseDouble(str);
        
        if (p < 0 || p > 0.5){
            System.out.println("P must be between 0 and 0.5 and is: " + p);
        }
    }//GEN-LAST:event_jErrorActionPerformed

    private void jRowBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRowBoxActionPerformed
        // TODO add your handling code here:
        System.out.println("Selected item row = " + jRowBox.getSelectedItem());
    }//GEN-LAST:event_jRowBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGF;
    private javax.swing.JButton jButtonColumnDecode;
    private javax.swing.JButton jButtonGMatrix;
    private javax.swing.JButton jButtonGenCW;
    private javax.swing.JButton jButtonRowDecode;
    private javax.swing.JButton jButtonSendZero;
    private javax.swing.JButton jButtonShowInfo;
    private javax.swing.JButton jButtonShowProperties;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jColumnBox;
    private javax.swing.JTextField jError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JRadioButton jRadioButtonGF2;
    private javax.swing.JRadioButton jRadioButtonGF3;
    private javax.swing.JRadioButton jRadioButtonGF8;
    private javax.swing.JComboBox<String> jRowBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    // End of variables declaration//GEN-END:variables
}
